### ISSUE TITLE
Should accept only 2 MB File size for Pdf

### ISSUE THREAD

**Issue by dhanarose** [Sundar-Infographic-Analytics/LMS#15]
![2024-01-23_10-30](https://github.com/Sundar-Infographic-Analytics/LMS/assets/100896935/89ac8586-b63d-449f-932e-ab043726a7c3)

**Comment by dhivagarinfographicanalytics** [comment]
As discussed with Sathya and Prabhu sir, the file size limit has been set to 5 MB
