### ISSUE TITLE
spell error

### ISSUE THREAD

**Issue by dhanarose** [Sundar-Infographic-Analytics/LMS#19]
![2024-01-23_14-04](https://github.com/Sundar-Infographic-Analytics/LMS/assets/100896935/2342b70b-e915-4e65-ba89-87b5c0797098)

**Comment by dhanarose** [comment]
![2024-01-23_14-20](https://github.com/Sundar-Infographic-Analytics/LMS/assets/100896935/7412462c-4d9a-4451-a331-918a1737fcce)

**Comment by dhivagarinfographicanalytics** [comment]
it's developer's option for the route
