### ISSUE TITLE
Remove unwanted console elements -- Check all pages

### ISSUE THREAD

**Issue by dhanarose** [Sundar-Infographic-Analytics/LMS#20]
![2024-01-23_14-07](https://github.com/Sundar-Infographic-Analytics/LMS/assets/100896935/4f48a2b2-4438-462b-b816-ca11ce714862)
![2024-01-23_14-08](https://github.com/Sundar-Infographic-Analytics/LMS/assets/100896935/935687ef-667b-440b-9754-6f1cdd7e5a32)
![2024-01-23_14-08_1](https://github.com/Sundar-Infographic-Analytics/LMS/assets/100896935/33e6b397-18e6-4188-896d-00b863957c2e)

**Comment by dhivagarinfographicanalytics** [comment]
I will remove it after addressing all the bugs.
