### ISSUE TITLE
Not as per design

### ISSUE THREAD

**Issue by dhanarose** [Sundar-Infographic-Analytics/LMS#21]
![2024-01-23_14-15](https://github.com/Sundar-Infographic-Analytics/LMS/assets/100896935/409e669d-9a11-4c91-926e-2970394d8cae)
![2024-01-23_14-15_1](https://github.com/Sundar-Infographic-Analytics/LMS/assets/100896935/3f9c528b-da03-4844-ad0c-8c884e7c0ce4)
![2024-01-23_14-17](https://github.com/Sundar-Infographic-Analytics/LMS/assets/100896935/40616a5d-ccdb-4b44-b8ea-a8b2e89e3415)

**Comment by dhanarose** [comment]
![2024-01-23_14-18](https://github.com/Sundar-Infographic-Analytics/LMS/assets/100896935/aa8880fa-948f-48f8-92dc-124684e01aa5)
![2024-01-23_14-18_1](https://github.com/Sundar-Infographic-Analytics/LMS/assets/100896935/5d64b4a9-0cd2-4fc0-8d24-d1a10d1eb41c)

**Comment by dhivagarinfographicanalytics** [comment]
This layout has been changed after figma design by discussion with prabhu.
