### ISSUE TITLE
Accepts excel file to upload - but not shown in preview page

### ISSUE THREAD

**Issue by dhanarose** [Sundar-Infographic-Analytics/LMS#22]
![2024-01-23_17-07](https://github.com/Sundar-Infographic-Analytics/LMS/assets/100896935/81807807-6b68-4f2d-8a92-c6a6e1ef7525)
![2024-01-23_17-08](https://github.com/Sundar-Infographic-Analytics/LMS/assets/100896935/7c40dae3-3177-468b-8781-97448df08c0f)

**Comment by dhivagarinfographicanalytics** [comment]
restricted for excel format
