### ISSUE TITLE
Loading indication should be placed at center (my course page) -- (MOBILE VIEW)

### ISSUE THREAD

**Issue by dhanarose** [Sundar-Infographic-Analytics/LMS#27]
![2024-01-24_11-50](https://github.com/Sundar-Infographic-Analytics/LMS/assets/100896935/453980e8-d8be-4bab-b1ff-482e910648b8)

**Comment by dhivagarinfographicanalytics** [comment]
It's not a loader issue; there is an issue with the responsiveness of my course page. Since you've already addressed a responsive bug, it's not considered a valid bug.
