### ISSUE TITLE
Change "Recently viewed courses" to "Your Last Viewed Content"

### ISSUE THREAD

**Issue by dhanarose** [Sundar-Infographic-Analytics/LMS#32]
![2024-01-24_14-30](https://github.com/Sundar-Infographic-Analytics/LMS/assets/100896935/a83f95c0-d57c-4c10-b824-acfa28754a49)
![2024-01-24_14-30_1](https://github.com/Sundar-Infographic-Analytics/LMS/assets/100896935/18555279-8bb1-4846-9d18-fdc163358ebd)

**Comment by dhivagarinfographicanalytics** [comment]
Figma content is dummy; it has been replaced by the content writer assigned by Prabhu

**Comment by dhanarose** [comment]
fixed
