### ISSUE TITLE
On clicking a lesson with PDF file type -- shows empty (LAP VIEW)

### ISSUE THREAD

**Issue by dhanarose** [Sundar-Infographic-Analytics/LMS#38]
![2024-01-24_15-23](https://github.com/Sundar-Infographic-Analytics/LMS/assets/100896935/6fc6defa-68de-4206-8126-2ff9dc7bde56)

**Comment by dhivagarinfographicanalytics** [comment]
can't replicate this

**Comment by dhanarose** [comment]
Now getting the PDF
