### ISSUE TITLE
On clicking the menus on top of the video -- menu bar not working -(LAP VIEW)

### ISSUE THREAD

**Issue by dhanarose** [Sundar-Infographic-Analytics/LMS#39]
![2024-01-24_15-32](https://github.com/Sundar-Infographic-Analytics/LMS/assets/100896935/bb268551-493c-47f1-b30a-a4ed73d274a8)

**Comment by dhivagarinfographicanalytics** [comment]
please replicate this again.... i tried many times to replicate

**Comment by subhaveera** [comment]
IT is replicating only in browser on device selection, but in Actual device it is not replicating so i suggest not to fix for this issue

**Comment by dhivagarinfographicanalytics** [comment]
it's working physical device (lap, mobile)
