### ISSUE TITLE
Alignment issue

### ISSUE THREAD

**Issue by dhanarose** [Sundar-Infographic-Analytics/LMS#42]
![2024-01-24_17-20_1](https://github.com/Sundar-Infographic-Analytics/LMS/assets/100896935/273058f8-c3e9-4b9a-8ff2-da9c478e6759)

**Comment by dhivagarinfographicanalytics** [comment]
I have fixed this. In my opinion, it would provide a better user experience to see a preview. I will discuss this with Prabhu sir
