### ISSUE TITLE
Change "No File Chosen" to "Choose file" -- Check all

### ISSUE THREAD

**Issue by dhanarose** [Sundar-Infographic-Analytics/LMS#47]
![2024-01-24_17-34](https://github.com/Sundar-Infographic-Analytics/LMS/assets/100896935/a5f53433-f808-4bda-b5a4-a9102db9c5e2)

**Comment by dhivagarinfographicanalytics** [comment]
Could not set Text Value for "No file Chosen" , See Attachment for reference
![Screenshot from 2024-01-25 15-37-56](https://github.com/Sundar-Infographic-Analytics/LMS/assets/141126688/ae0519df-89b5-4401-bf62-eb4a6556e719)

**Comment by dhanarose** [comment]
discussed with prabhu sir
