### ISSUE TITLE
After approving - editing the course - should ask approve again  - till approving  -  edit course should not update for the user

### ISSUE THREAD

**Issue by dhanarose** [Sundar-Infographic-Analytics/LMS#5]
![2024-01-19_12-32](https://github.com/Sundar-Infographic-Analytics/LMS/assets/100896935/9b3ca455-d6a4-473c-903f-5cd550b7b1a4)

**Comment by dhivagarinfographicanalytics** [comment]
flow has been changed as discussed  with all
